id: I931D6314
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:23:48+00:00'
last_modified: '2022-06-08T11:44:53.203388+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17218
  title: མཁན་ཆེན་རྡོ་རྗེ་འཆང་བློ་གྲོས་དྲི་མེད་མཆོག་གི་གསུང་མགུར་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    14EC:
      image_group_id: I1KG17903
      title: ''
      total_pages: 50
      order: 1
      base_file: 14EC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
